require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SentencesController do

  def mock_sentence(stubs={})
    @mock_sentence ||= mock_model(Sentence, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all sentences as @sentences" do
      Sentence.stub(:all) { [mock_sentence] }
      get :index
      assigns(:sentences).should eq([mock_sentence])
    end
  end

  describe "GET show" do
    it "assigns the requested sentence as @sentence" do
      Sentence.stub(:find).with("37") { mock_sentence }
      get :show, :id => "37"
      assigns(:sentence).should be(mock_sentence)
    end
  end

  describe "GET new" do
    it "assigns a new sentence as @sentence" do
      Sentence.stub(:new) { mock_sentence }
      get :new
      assigns(:sentence).should be(mock_sentence)
    end
  end

  describe "GET edit" do
    it "assigns the requested sentence as @sentence" do
      Sentence.stub(:find).with("37") { mock_sentence }
      get :edit, :id => "37"
      assigns(:sentence).should be(mock_sentence)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created sentence as @sentence" do
        Sentence.stub(:new).with({'these' => 'params'}) { mock_sentence(:save => true) }
        post :create, :sentence => {'these' => 'params'}
        assigns(:sentence).should be(mock_sentence)
      end

      it "redirects to the created sentence" do
        Sentence.stub(:new) { mock_sentence(:save => true) }
        post :create, :sentence => {}
        response.should redirect_to(sentence_url(mock_sentence))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sentence as @sentence" do
        Sentence.stub(:new).with({'these' => 'params'}) { mock_sentence(:save => false) }
        post :create, :sentence => {'these' => 'params'}
        assigns(:sentence).should be(mock_sentence)
      end

      it "re-renders the 'new' template" do
        Sentence.stub(:new) { mock_sentence(:save => false) }
        post :create, :sentence => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sentence" do
        Sentence.stub(:find).with("37") { mock_sentence }
        mock_sentence.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :sentence => {'these' => 'params'}
      end

      it "assigns the requested sentence as @sentence" do
        Sentence.stub(:find) { mock_sentence(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:sentence).should be(mock_sentence)
      end

      it "redirects to the sentence" do
        Sentence.stub(:find) { mock_sentence(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(sentence_url(mock_sentence))
      end
    end

    describe "with invalid params" do
      it "assigns the sentence as @sentence" do
        Sentence.stub(:find) { mock_sentence(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:sentence).should be(mock_sentence)
      end

      it "re-renders the 'edit' template" do
        Sentence.stub(:find) { mock_sentence(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sentence" do
      Sentence.stub(:find).with("37") { mock_sentence }
      mock_sentence.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the sentences list" do
      Sentence.stub(:find) { mock_sentence }
      delete :destroy, :id => "1"
      response.should redirect_to(sentences_url)
    end
  end

end
